### ISSUE TITLE
CREATE research_ave_boost not work

### ISSUE THREAD

**Issue by processadd** [mtpatter/postgres-kafka-demo#2]
Hi, 
Below syntax works (WITH statement)?
CREATE TABLE research_ave_boost AS \
     SELECT research, SUM(admit_chance)/COUNT(admit_chance) as ave_chance \
     FROM research_boost \
     WITH (KAFKA_TOPIC='research_ave_boost', VALUE_FORMAT='delimited', KEY='research') \
     GROUP BY research;
Thanks
Brad

**Comment by philipz** [comment]
CREATE TABLE research_ave_boost \
WITH (KAFKA_TOPIC='research_ave_boost', VALUE_FORMAT='delimited') \
AS SELECT research, SUM(admit_chance)/COUNT(admit_chance) as ave_chance \
FROM research_boost \
GROUP BY research;
[KSQL Syntax Reference](https://docs.confluent.io/current/ksql/docs/developer-guide/syntax-reference.html#create-table-as-select)
